OUTPUT_DIR = config["output_dir"]
rule FETCH_GENOME:
    output:
        os.path.join(OUTPUT_DIR,"rule_FETCH_GENOME","download.done.txt")
    shell:
        """
        lftp -c "open https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.40_GRCh38.p14/; mirror -e . ./OUTPUT_DIR/rule_FETCH_GENOME"
        cd ./OUTPUT_DIR/rule_FETCH_GENOME
        gunzip *.gz
        """


